In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot


In [6]:
from libKMCUDA import kmeans_cuda

In [14]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

full_csv = "/mnt/data/SCALABLE/HARRISON/pca/full.csv"
df = pd.read_csv(full_csv, sep=",", header=None, index_col=0)
print("DATASET LOADED")

scaler = MinMaxScaler(feature_range=[0, 1])
data_rescaled = scaler.fit_transform(df)
print(data_rescaled)
print("DATASET NORMALIZED")
#Fitting the PCA algorithm with our Data
pca_model = PCA(n_components=130).fit(data_rescaled)
print("PCA FIT")


DATASET LOADED
[[0.66424388 0.56606836 0.50727742 ... 0.62679593 0.61127706 0.54882931]
 [0.63996439 0.73253994 0.56657055 ... 0.5691039  0.5696665  0.63104607]
 [0.69608707 0.74612231 0.53833612 ... 0.50491309 0.54635844 0.65518444]
 ...
 [0.66554482 0.70617891 0.5890896  ... 0.56739975 0.73123677 0.76174836]
 [0.65692766 0.73210897 0.50131871 ... 0.56785813 0.65907677 0.67341439]
 [0.67561254 0.72804485 0.56012496 ... 0.57527451 0.67883786 0.62172116]]
DATASET NORMALIZED
PCA FIT


In [17]:
import pickle
pickle.dump(pca_model, open('pca_model.pickle', 'wb'))

In [64]:
pickle.dump(scaler, open('scaler.pickle', 'wb'))

In [18]:
pca_arr = pca_model.transform(data_rescaled)

In [22]:
print(pca_arr[0])

[ 3.12432963e-01 -1.04179531e+00 -5.81344170e-01  8.25516843e-01
  1.19773258e+00  5.42017534e-02 -4.01070751e-01 -4.81321118e-02
 -5.89404607e-01  7.81964206e-01 -4.98436574e-01  1.67939673e-01
 -1.76223754e+00  1.30231297e-01  3.22969089e-01 -4.45078744e-02
  1.31161112e-01 -2.62203441e-01  4.17634282e-02 -3.75637576e-01
 -5.58989406e-01 -7.04312786e-01 -2.12056410e-02 -3.44439815e-01
  2.02940733e-01 -2.76587065e-01  3.37578238e-01  7.31284432e-04
  5.74775451e-02  2.59248560e-01  1.26137279e-01 -6.32594248e-02
  9.88131131e-01 -3.69802418e-01  1.74607340e-01 -1.24009167e-01
  4.02667404e-02 -4.15449033e-01  2.62635179e-01  2.23535329e-01
 -2.29182812e-01  6.24029815e-01  3.24639802e-02  2.39205723e-01
 -2.32283613e-01 -1.17474965e-01  1.47937884e-01  6.76836145e-02
 -8.82700357e-02  3.61094322e-01  3.56859047e-02  9.08291870e-02
  4.04679493e-01 -1.76940784e-01 -1.59571078e-02 -3.90178770e-02
 -2.16748506e-02 -1.03200094e-01  1.41472432e-01 -2.35894206e-01
  2.92014582e-01  2.31944

In [31]:
data = pd.DataFrame(pca_arr).to_csv("/mnt/data/SCALABLE/HARRISON/pca/pca_130_new.csv", header=None, index=None)


In [32]:
path = "/mnt/data/SCALABLE/HARRISON/pca/pca_130_new.csv"


In [33]:
arr = pd.read_csv(path, sep=",", header=None, index_col=None, dtype="float16")
arr = arr.to_numpy()


In [34]:
print(arr.shape)

(57381, 130)


In [38]:
centroids, assignments = kmeans_cuda(
    arr, 169, metric="L2", verbosity=1, seed=3)

In [36]:
#Dizionario con come chiave il centroide e come valore la lista di punti corrispondenti.
points_centroids_map = {x: [] for x in range(0,169)}
for index, item in enumerate(assignments):
    points_centroids_map[item].append(index)

In [41]:
pickle.dump(points_centroids_map, open('points_centroids_map.pickle', 'wb'))
pickle.dump(centroids, open('centroids.pickle', 'wb'))
pickle.dump(assignments, open('assignments.pickle', 'wb'))


In [86]:
#punti medi per centroide
sum = 0
for k, v in points_centroids_map.items():
    sum += len(v)
    print("K:", k)
    print("V;", len(v))

mean = sum / 169
print(mean)

K: 0
V; 179
K: 1
V; 401
K: 2
V; 396
K: 3
V; 630
K: 4
V; 449
K: 5
V; 123
K: 6
V; 239
K: 7
V; 556
K: 8
V; 248
K: 9
V; 344
K: 10
V; 430
K: 11
V; 0
K: 12
V; 76
K: 13
V; 317
K: 14
V; 448
K: 15
V; 224
K: 16
V; 863
K: 17
V; 225
K: 18
V; 550
K: 19
V; 140
K: 20
V; 28
K: 21
V; 183
K: 22
V; 435
K: 23
V; 661
K: 24
V; 243
K: 25
V; 442
K: 26
V; 303
K: 27
V; 85
K: 28
V; 415
K: 29
V; 192
K: 30
V; 137
K: 31
V; 492
K: 32
V; 585
K: 33
V; 570
K: 34
V; 361
K: 35
V; 538
K: 36
V; 129
K: 37
V; 735
K: 38
V; 95
K: 39
V; 234
K: 40
V; 63
K: 41
V; 158
K: 42
V; 373
K: 43
V; 430
K: 44
V; 334
K: 45
V; 351
K: 46
V; 316
K: 47
V; 401
K: 48
V; 303
K: 49
V; 268
K: 50
V; 311
K: 51
V; 253
K: 52
V; 499
K: 53
V; 425
K: 54
V; 79
K: 55
V; 439
K: 56
V; 201
K: 57
V; 230
K: 58
V; 528
K: 59
V; 190
K: 60
V; 390
K: 61
V; 293
K: 62
V; 86
K: 63
V; 514
K: 64
V; 253
K: 65
V; 668
K: 66
V; 266
K: 67
V; 0
K: 68
V; 285
K: 69
V; 174
K: 70
V; 284
K: 71
V; 232
K: 72
V; 85
K: 73
V; 147
K: 74
V; 375
K: 75
V; 249
K: 76
V; 452
K: 77
V; 395
K: 78
V;

In [46]:
#Parte per estrarre features immagine:
import sys
import torch
import pretrainedmodels.utils as utils
import pretrainedmodels

from io import BytesIO
from PIL import Image

import requests

load_img = utils.LoadImage()
torch.set_printoptions(precision=20)

model_name = 'alexnet'
model = pretrainedmodels.__dict__[model_name](num_classes=1000, pretrained='imagenet')

tf_img = utils.TransformImage(model)

In [48]:
def get_vector(image_name):
    if image_name.startswith("http"):
        response = requests.get(image_name)
        input_img = Image.open(BytesIO(response.content))

    else:
        input_img = load_img(image_name)
    input_tensor = tf_img(input_img)
    input_tensor = input_tensor.unsqueeze(0)
    input = torch.autograd.Variable(input_tensor, requires_grad=False)
    output_features = model.features(input).view(4096)
    return output_features.data.numpy()

In [65]:
test = get_vector("https://image.ibb.co/kYdbKT/IMG_20180725_194058_490.jpg").reshape(1,-1)

In [67]:
test_scaled = scaler.transform(test)

In [68]:
print(test.shape)
test_pca = pca_model.transform(test_scaled)
print(test_pca.shape)

(1, 4096)
(1, 130)


In [104]:
def get_distances(point, points):
    sP = points
    pA = point
    return np.linalg.norm(sP - pA, ord=2, axis=1.)  # 'distances' is a list

#def get_closest_centroid2(array,centroids):
    

c = np.nanargmin(get_distances(test_pca, centroids))


    
    

In [105]:
print(c)

31


In [155]:
print(np.linalg.norm(test_pca-centroids[31]))

2.8025629705307114


In [84]:
from scipy.spatial import distance
print(distance.euclidean(test_pca, centroids[168]))


9.973279913582314


In [136]:
def indexlist_to_points(lst,dataset):
    points = np.empty([len(lst),dataset.shape[1]])
    for index, val in enumerate(lst):
        points[index] = dataset[val]
    return points
        

cimg = indexlist_to_points(points_centroids_map[c],arr)      
#dist_points = get_distances(test_pca, points_centroids_map[c] )

In [230]:
#cerchiamo l'immagine più vicina tra quelle appartenenti al centroide!

dist2 = get_distances(test_pca,cimg)
d_c = np.argsort(dist2)
smallest = d_c[:5]

nearest_sample = []
for s in smallest:
    nearest_sample.append(points_centroids_map[c][np.asscalar(s)])


In [222]:
import csv
hashtags = []
with open("/mnt/data/SCALABLE/HARRISON/pca/tag_list_clean.csv", "r") as csvFile: 
    reader = csv.reader(csvFile,delimiter = " ")
    for row in reader:
        hashtags.append(row)


In [231]:
for n in nearest_sample:
    print(hashtags[n])

['arianagrande', 'selenagomez', 'mileycyrus', 'justinbieber']
['orange', 'yellow', 'favorite']
['boy', 'girl', 'sfs']
['work', 'tired', 'goodnight']
['boy', 'instachile']
